### ISSUE TITLE
Unable to create a themed frame without border (border==0)

### ISSUE THREAD

**Issue by arielvb** [Moguri/bgui#2]
If you want to override the border of a themed frame to size 0 when creating a new frame `bgui.Frame(...,border=0)` the frame will use the border theme value.

You can reproduce this following the next steps:
- Modify the border color for frames on the default theme.cfg, for example to red  https://github.com/Moguri/bgui/blob/master/themes/default/theme.cfg#L17
   `BorderColor=1, 0.0, 0.0, 1.0`
- Modify the example _simple_ to create the win without frame on https://github.com/Moguri/bgui/blob/master/examples/simple/blender_test.py#L22 to:
   `self.win = bgui.Frame(self, size=[0.6, 0.8], border=0,`

**Comment by Moguri** [comment]
Thanks for the fix!
