### ISSUE TITLE
TextInput highlight and cursor not displaying correctly(fixed in my fork)

### ISSUE THREAD

**Issue by Remwrath** [Moguri/bgui#8]
The TextInput highlight and cursor was using absolute pixel sizes and positions instead of normalized, thanks to MikePan getting a quick solution to set the highlight and cursor in TextInput to no_normalize, you will find the fix in my fork of bgui.

**Comment by Moguri** [comment]
Could you do a pull request?

**Comment by Remwrath** [comment]
I Have already created a pull request as far as I understand
